name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
        env:
          DOPPLER_TOKEN: ${{ secrets.TEST_DOPPLER_TOKEN }}
